version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
      - "/app/node_modules"
    depends_on:
      - mysql_server
    env_file:
      - ./.env

  mysql_server:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=tokopaedi
      - MYSQL_ROOT_PASSWORD=123456
    env_file:
      - ./.env
