version: "3.8"

services:
  app:
    container_name: tokopaedi-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - mysql_server

  mysql_server:
    container_name: tokopaedi-mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    volumes:
      - db-data:/var/lib/mysql
      
volumes:
  db-data: