version: "3.8"

services:
  backend_app:
    command: bash -c 'while !</dev/tcp/mysql_server/3306; do sleep 1; done; npm run dev:docker'
    deploy: 
      replicas: 3
    volumes:
      - "/backend_app/node_modules"
    env_file:
      - ./.env.dockerdev

  mysql_server:
    ports:
      - 3307:3306
    env_file:
      - ./.env.dockerdev